### ISSUE TITLE
Comments on current code

### ISSUE THREAD

**Issue by nspruit** [thegeman/FDDG#28]
Here are some comments I have on the current codebase: 
- [x] The package names (`nl.tud`) are not really unique. Something like `nl.tud.dcs.fddg` will be much better. (fixed in #29)
- [x]  The code is currently not documented that well. I think that at least all interface methods (and preferably all other public methods as well) need a JavaDoc comment to inform each other about what the method does and why it is there (so it also documents the protocol). Now, you cannot see what some methods actually do without examining the code. (Fixed in #32)
- [x] With the current Main class you can only start all servers and clients on the same machine. However, we need to be able to distribute them across multiple machines to actually make it a distributed system. I suggest we do this by having a main method that only starts one server on the local machine. Then we can actually start each server on another machine. The same holds for the client processes. We can then also use scripts to for instance start x clients on one machine. (fixed in #31)
- [x] In the current Main class the IDs of the clients are randomly generated. This is not really correct as multiple clients can now have the same ID. Instead, the clients should receive their ID from the server (and not pick one themselves). (fixed in #39)
- [x] I think the GUI of a server should be optional so that you can also start one without a GUI. Currently, a new GUI is created for every server.(fixed in #31)
- [x] Why do we wait 5 seconds (and 1 second in the loop) in `ServerProcess.run()`? This is an example of where a comment should  clarify this ;) (fixed in 2082fd7d87a7d79aa0ad1b270b22abe25330fa36)
- [x] This (in `ServerProcess.connect()`) is not going to work when the clients run on different machines: `ClientInterface ci = (ClientInterface) Naming.lookup("rmi://localhost:" + Main.SERVER_PORT + "/FDDGClient/" + playerId);` (fixed in #47)
- [x] `ServerProcess.broadcastFieldToConnectedPlayers()` does not meet our design as the entire field is only sent once to each client (when he connects), so it will never be broadcast. This is probably related to issue #24 
- [x] I think the `XAction` classes do not really represent game objects, so I would put them in another package. (fixed in #29)
- [x] For creating a copy of the path in `Field.getDirectionToNearestDragon()` you can better use the copy constructor of ArrayList (so `new ArrayList<>(path)`) instead of: `ArrayList<Integer> updatedPath = new ArrayList<Integer>(path.size());
                     for(int pos : path){
                         updatedPath.add(pos);
                     }` (fixed in #29)
- [x] The `Field.dragonRage()` function should be replaced because this function only works when there is only one server. With multiple servers, the game state will become inconsistent. Perhaps only perform the rage on the players that have connected to the particular server. Then there is no need for sending messages to other servers. (fixed in #47)
